import SwiftUI

struct PrivacyDetailView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: Spacing.l) {
                header

                Group {
                    section(
                        symbol: "iphone",
                        title: "Where your entries live",
                        body: "Every word you write is stored on this iPhone in the app's private database. Photo and audio attachments are saved to the app's sandbox. None of it is uploaded anywhere by Inkling."
                    )

                    section(
                        symbol: "sparkles",
                        title: "How the AI features work",
                        body: "Daily prompts, mood suggestions, and weekly reflections are generated by Apple Intelligence, which runs entirely on your device. Your text is never sent to OpenAI, Google, Anthropic, or anyone else — including Apple's servers. If Apple Intelligence isn't available, Inkling falls back to a curated set of prompts bundled with the app."
                    )

                    section(
                        symbol: "icloud",
                        title: "iCloud sync (optional, off by default)",
                        body: "If you turn on iCloud sync in Settings, your entries sync through your own iCloud account using Apple's CloudKit. We don't see them. Apple stores them in your iCloud the same way it stores your Notes."
                    )

                    section(
                        symbol: "chart.bar.xaxis",
                        title: "Analytics",
                        body: "Inkling does not include any analytics SDK. We don't know which prompts you tap, which entries you write, or how often you open the app."
                    )

                    section(
                        symbol: "location.slash",
                        title: "Location",
                        body: "If you choose to attach a place to an entry, Inkling stores only the city or place name — never your exact coordinates."
                    )
                }

                Text("This is a promise we want to keep verifiable. Anyone can search the source for `URLSession` and find no calls in the entry or AI paths.")
                    .font(.footnote)
                    .foregroundStyle(.secondary)
                    .padding(.top, Spacing.m)
            }
            .padding(Spacing.l)
        }
        .navigationTitle("Privacy")
        .navigationBarTitleDisplayMode(.inline)
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: Spacing.s) {
            Image(systemName: "lock.shield")
                .font(.system(size: 40, weight: .light))
                .foregroundStyle(Color.inkAccent)
            Text("Yours, and only yours")
                .font(.system(.title, design: .serif).weight(.semibold))
            Text("Plain English about where your data lives.")
                .font(.callout)
                .foregroundStyle(.secondary)
        }
    }

    private func section(symbol: String, title: String, body: String) -> some View {
        VStack(alignment: .leading, spacing: Spacing.s) {
            HStack(spacing: Spacing.s) {
                Image(systemName: symbol)
                    .foregroundStyle(Color.inkAccent)
                Text(title)
                    .font(.callout.weight(.semibold))
            }
            Text(body)
                .font(.callout)
                .foregroundStyle(.primary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(Spacing.m)
        .background(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .fill(Color.inkSecondary.opacity(0.6))
        )
    }
}
